version: "3.8"
services:
  backend:
    container_name: auth_backend
    image: node:12
    working_dir: /home/node/app
    command: [ "npm", "run", "start:app" ]
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app
      - ~/.config/gcloud:/home/.config/gcloud
    environment:
      NODE_ENV: "development"
    networks:
      - default

  db:
    container_name: auth_db
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: auth
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./docker/local:/docker-entrypoint-initdb.d
    networks:
      - default

networks:
  default:
    name: auth
